# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e47223a6c546e763081aec279ee46e1"
application_url = "https://example.com"
embedded = true
name = "Drop Countdown Lite"

[access_scopes]
scopes = "read_products,read_publications,write_publications"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
